In [1]:
import numpy

In [9]:
n = numpy.arange(27)

### Создает последовательность из 27 чисел начиная с 0

In [10]:
print(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26]


### Переформирует ее в трехмерный массив

In [15]:
n = n.reshape(3,3,3)
n

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [14]:
n.shape

(3, 3, 3)

### Создает двумерный массив

In [7]:
m = numpy.asarray([[123,12,213,12,35],[],[]])

In [9]:
print(m)

[list([123, 12, 213, 12, 35]) list([]) list([])]


In [29]:
import cv2

### Представляет рисунок как трехмерный массив, 1 - для пресдтавления в RGB, 0 - в чб

In [30]:
im_g = cv2.imread ("smallgray.png", 1)
im_g

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

### Переводит массив в рисунок

In [13]:
cv2.imwrite("newsmallgray.png", im_g)

True

In [34]:
im_g = cv2.imread ("smallgray.png", 0)
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [21]:
im_g[:,2:4]

array([[104, 121],
       [255, 255],
       [255,  97]], dtype=uint8)

In [31]:
for i in im_g:
    print(i)

[[187 187 187]
 [158 158 158]
 [104 104 104]
 [121 121 121]
 [143 143 143]]
[[198 198 198]
 [125 125 125]
 [255 255 255]
 [255 255 255]
 [147 147 147]]
[[209 209 209]
 [134 134 134]
 [255 255 255]
 [ 97  97  97]
 [182 182 182]]


### .Т - транспонирует массив, flat - представляет массив как последовательность цифр и выводит по одной

In [24]:
for i in im_g.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [25]:
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [43]:
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

### Объединяет массивы. hstack - горизонтально, vstack - вертикально

In [39]:
ims = numpy.hstack((im_g, im_g, im_g))

In [40]:
ims

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143, 187, 158, 104,
        121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147, 198, 125, 255,
        255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182, 209, 134, 255,
         97, 182]], dtype=uint8)

In [41]:
ims = numpy.vstack((im_g, im_g, im_g))

In [48]:
ims

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

### Разбивает массив на несколько. hsplit - горизонтально, построчно, vsplit - вертикально, по столбцам

In [44]:
lst = numpy.hsplit(ims, 5)

In [45]:
lst

[array([[187],
        [198],
        [209],
        [187],
        [198],
        [209],
        [187],
        [198],
        [209]], dtype=uint8), array([[158],
        [125],
        [134],
        [158],
        [125],
        [134],
        [158],
        [125],
        [134]], dtype=uint8), array([[104],
        [255],
        [255],
        [104],
        [255],
        [255],
        [104],
        [255],
        [255]], dtype=uint8), array([[121],
        [255],
        [ 97],
        [121],
        [255],
        [ 97],
        [121],
        [255],
        [ 97]], dtype=uint8), array([[143],
        [147],
        [182],
        [143],
        [147],
        [182],
        [143],
        [147],
        [182]], dtype=uint8)]

In [46]:
lst = numpy.vsplit(ims, 3)

In [47]:
lst

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]

### Создает массив из одних нулей

In [4]:
numpy.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [5]:
numpy.ones(4)

array([ 1.,  1.,  1.,  1.])

### Создает массив, содержащий числа между двумя заданными числами с заданным интервалом (по сути линейная функция)

In [7]:
numpy.linspace(0,5,10)

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

### Создает квадратную единичную матрицу

In [11]:
numpy.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

### Создает матрицу заданных размеров из сучайных чисел, которые образуют нормальное распределение на отрезке [0,1]

In [13]:
numpy.random.rand(5)

array([ 0.59816928,  0.36957796,  0.79136833,  0.34553097,  0.4094872 ])

### Как rand, только со стандарнтынм нормальным распределением

In [16]:
numpy.random.randn(2)

array([ 0.47955   ,  1.82583226])

### Создает массив из случайных чисел в заданном диапазоне (не считая первое и последнее)

In [2]:
ranarr = numpy.random.randint(1,100,10)
ranarr

array([21, 98, 17, 85, 96, 50, 58,  5, 63, 30])

### Находит минимум и максимум в массиве

In [4]:
ranarr.max()

98

In [16]:
ranarr.min()

5

### Выводит место минимального и максимального элемента  в массиве

In [6]:
ranarr.argmax()

1

In [17]:
ranarr.argmin()

7

### Показывает тип данных в массиве

In [19]:
ranarr.dtype

dtype('int64')

### Array indexing

In [21]:
arr = numpy.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
arr[8]

8

In [23]:
arr[1:5]

array([1, 2, 3, 4])

In [24]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [26]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [27]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [37]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,  99,   6,   7,   8,   9,  10])

### Array slicing. Когда изменяется срез массива, изменяется и сама эта часть массива

In [33]:
arr = numpy.arange(0,11)
slice_of_arr = arr[0:6]

In [39]:
slice_of_arr

array([100, 100, 100, 100, 100,  99])

In [40]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [41]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

### Создает копию массива. Изменения в копии не влияют на сам исходный массив

In [42]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [43]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [44]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

### Indexing in 2d array

In [46]:
arr_2d = numpy.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [49]:
arr_2d[0][0]

5

In [51]:
arr_2d[0]

array([ 5, 10, 15])

In [52]:
arr_2d[1][1]

25

In [53]:
arr_2d[2][1]

40

In [54]:
arr_2d[2,1]

40

In [55]:
arr_2d[1,2]

30

In [65]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [67]:
arr_2d_1 = numpy.arange(50).reshape(5,10)
arr_2d_1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [68]:
arr_2d_1[1:3,3:5]

array([[13, 14],
       [23, 24]])

### Conditional slicing of arrays

In [59]:
arr = numpy.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
bool_arr = arr > 5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [62]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [63]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [69]:
arr[arr<3]

array([1, 2])

### Numpy operations

In [70]:
arr = numpy.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [71]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [72]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [73]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [74]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [75]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [76]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [78]:
arr/arr

/home/anzh/miniconda3/envs/udemy/lib/python3.5/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.])

In [79]:
1/arr

/home/anzh/miniconda3/envs/udemy/lib/python3.5/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([        inf,  1.        ,  0.5       ,  0.33333333,  0.25      ,
        0.2       ,  0.16666667,  0.14285714,  0.125     ,  0.11111111,
        0.1       ])

In [80]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [81]:
numpy.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [82]:
numpy.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [83]:
numpy.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [84]:
numpy.log(arr)

/home/anzh/miniconda3/envs/udemy/lib/python3.5/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436,
        1.60943791,  1.79175947,  1.94591015,  2.07944154,  2.19722458,
        2.30258509])

### The list of functions with arrays: https://docs.scipy.org/doc/numpy/reference/ufuncs.html